name: atomik-trading
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
    source_dir: backend  # Assuming you move Django files to a backend directory
    build_command: pip install -r requirements.txt
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_TIME
        value: core.settings
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}  # DO will inject this
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: ${APP_DOMAIN}
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET

databases:
  - engine: PG
    name: db
    version: "12"

static_sites:
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
    source_dir: frontend  # Assuming you move React files to a frontend directory
    build_command: npm install && npm run build
    output_dir: build
    routes:
      - path: /