name: landingpage
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: elcapitan88/landingpage
  dockerfile_path: Dockerfile
  http_port: 8000
  health_check:
    http_path: /health/
    port: 8000
    initial_delay_seconds: 30