name: landingpage
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health/
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: core.settings
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app"
  - key: DEBUG
    value: "False"