name: atomik-trading
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    instance_count: 1
    instance_size_slug: basic-xxs
    environment_slug: python
    envs:
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_TIME
        value: core.settings
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        value: ${APP_DOMAIN}
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ${APP_DOMAIN}

  - name: frontend
    github:
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm install && npm run build
    run_command: serve -s build
    instance_count: 1
    instance_size_slug: basic-xxs
    environment_slug: node-js

databases:
  - engine: PG
    name: db
    version: "12"