name: atomik-trading
services:
  - name: api
    source_dir: backend
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000
    instance_size_slug: basic-xxs
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        type: SECRET
      - key: STRIPE_SECRET_KEY
        type: SECRET

databases:
  - engine: PG
    name: db
    version: "12"