@"
name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpage
    source_dir: backend
    envs:
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "True"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: "*"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: "core.settings"
      - key: PYTHONUNBUFFERED
        scope: RUN_AND_BUILD_TIME
        value: "1"
    http_port: 8000
    instance_size_slug: basic-xs
    build_command: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    run_command: |
      dir
      cd
      gunicorn -c gunicorn_config.py
"@ | Out-File -FilePath app.yaml -Encoding utf8