name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpageprjct
    source_dir: backend
    envs:
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ".ondigitalocean.app,api.atomiktrading.com"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: "core.settings"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SECRET_KEY}
      - key: CORS_ALLOWED_ORIGINS
        scope: RUN_AND_BUILD_TIME
        value: "https://atomiktrading.com,https://www.atomiktrading.com"
      - key: APP_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: "atomiktrading.com"
      - key: DISABLE_COLLECTSTATIC
        scope: RUN_AND_BUILD_TIME
        value: "1"
    http_port: 8000
    instance_size_slug: basic-xs
    build_command: >
      pip install -r requirements.txt
    run_command: >
      cd /workspace/backend && 
      python manage.py migrate --noinput &&
      gunicorn --chdir /workspace/backend core.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --log-level debug