name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpageprjct
    source_dir: backend
    instance_size_slug: basic-xs
    build_command: pip install -r requirements.txt
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONPATH
        value: .
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: NO_COLLECTSTATIC
        value: "1"
      - key: PORT
        value: "8000"
    http_port: 8000