name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpage
    source_dir: backend
    instance_size_slug: basic-xs
    build_command: pip install -r requirements.txt
    run_command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2