name: atomik-trading
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    source_dir: /
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ${APP_DOMAIN}
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SECRET_KEY}
      - key: STRIPE_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${STRIPE_SECRET_KEY}
      - key: STRIPE_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${STRIPE_PUBLISHABLE_KEY}
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${STRIPE_WEBHOOK_SECRET}
      - key: STRIPE_LIFETIME_PRICE_ID
        scope: RUN_AND_BUILD_TIME
        value: ${STRIPE_LIFETIME_PRICE_ID}
      - key: FRONTEND_URL
        scope: RUN_AND_BUILD_TIME
        value: ${FRONTEND_URL}
    http_port: 8000
    instance_size_slug: basic-xs
    routes:
      - path: /
    buildCommand: bash build.sh
    startCommand: gunicorn --workers 2 --timeout 120 core.wsgi:application

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: basic-xs
    version: "14"