name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpageprjct
    source_dir: backend
    envs:
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ".ondigitalocean.app,api.atomiktrading.com"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: "core.settings"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SECRET_KEY}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "8000"
    instance_size_slug: basic-xs
    build_command: pip install -r requirements.txt