name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpage
    source_dir: backend
    envs:
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "True"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: "*"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: "core.settings"
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SECRET_KEY}
      - key: PYTHONPATH
        scope: RUN_AND_BUILD_TIME
        value: "."
    http_port: 8000
    instance_size_slug: basic-xs
    build_command: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    run_command: |
      python -m pip install gunicorn
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 2 --log-level debug