name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpageprjct
    source_dir: backend
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONPATH
        value: /workspace/backend
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "*"
    instance_size_slug: basic-xs
    http_port: 8000
    run_command: python manage.py runserver 0.0.0.0:8000