name: atomik-trading-backend
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: elcapitan88/landingpage
    source_dir: backend
    envs:
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "True"
      - key: ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: "*"
      - key: DJANGO_SETTINGS_MODULE 
        scope: RUN_AND_BUILD_TIME
        value: "core.settings"
      - key: NO_COLLECTSTATIC
        scope: RUN_AND_BUILD_TIME
        value: "1"
      - key: DISABLE_COLLECTSTATIC
        scope: RUN_AND_BUILD_TIME
        value: "1"
    instance_size_slug: basic-xs
    http_port: 8000
    build_command: pip install -r requirements.txt
    run_command: gunicorn --bind 0.0.0.0:$PORT --workers=2 core.wsgi:application