# Generated by Django 5.1.1 on 2024-11-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prelaunch', '0003_lifetimemembershipconfig_prelaunch_l_is_acti_093acf_idx'),
        ('prelaunch', '0003_update_initial_spots'),
    ]

    operations = [
    ]
